// <auto-generated />
using System;
using JournalApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JournalApp.Migrations
{
    [DbContext(typeof(JournalDbContext))]
    [Migration("20251221062524_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("JournalApp.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryMoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondaryMood1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondaryMood2Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryMoodId");

                    b.HasIndex("SecondaryMood1Id");

                    b.HasIndex("SecondaryMood2Id");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("JournalApp.Models.Mood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Emoji = "😊",
                            Name = "Happy"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Emoji = "🤗",
                            Name = "Excited"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Emoji = "😌",
                            Name = "Relaxed"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Emoji = "🙏",
                            Name = "Grateful"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            Emoji = "💪",
                            Name = "Confident"
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            Emoji = "😐",
                            Name = "Calm"
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            Emoji = "🤔",
                            Name = "Thoughtful"
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Emoji = "🧐",
                            Name = "Curious"
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            Emoji = "😌",
                            Name = "Nostalgic"
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            Emoji = "😑",
                            Name = "Bored"
                        },
                        new
                        {
                            Id = 11,
                            Category = 2,
                            Emoji = "😔",
                            Name = "Sad"
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            Emoji = "😠",
                            Name = "Angry"
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            Emoji = "😰",
                            Name = "Stressed"
                        },
                        new
                        {
                            Id = 14,
                            Category = 2,
                            Emoji = "😢",
                            Name = "Lonely"
                        },
                        new
                        {
                            Id = 15,
                            Category = 2,
                            Emoji = "😟",
                            Name = "Anxious"
                        });
                });

            modelBuilder.Entity("JournalApp.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCustom = false,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 2,
                            IsCustom = false,
                            Name = "Career"
                        },
                        new
                        {
                            Id = 3,
                            IsCustom = false,
                            Name = "Studies"
                        },
                        new
                        {
                            Id = 4,
                            IsCustom = false,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 5,
                            IsCustom = false,
                            Name = "Friends"
                        },
                        new
                        {
                            Id = 6,
                            IsCustom = false,
                            Name = "Relationships"
                        },
                        new
                        {
                            Id = 7,
                            IsCustom = false,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 8,
                            IsCustom = false,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 9,
                            IsCustom = false,
                            Name = "Personal Growth"
                        },
                        new
                        {
                            Id = 10,
                            IsCustom = false,
                            Name = "Self-care"
                        },
                        new
                        {
                            Id = 11,
                            IsCustom = false,
                            Name = "Hobbies"
                        },
                        new
                        {
                            Id = 12,
                            IsCustom = false,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 13,
                            IsCustom = false,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 14,
                            IsCustom = false,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 15,
                            IsCustom = false,
                            Name = "Spirituality"
                        },
                        new
                        {
                            Id = 16,
                            IsCustom = false,
                            Name = "Birthday"
                        },
                        new
                        {
                            Id = 17,
                            IsCustom = false,
                            Name = "Holiday"
                        },
                        new
                        {
                            Id = 18,
                            IsCustom = false,
                            Name = "Vacation"
                        },
                        new
                        {
                            Id = 19,
                            IsCustom = false,
                            Name = "Celebration"
                        },
                        new
                        {
                            Id = 20,
                            IsCustom = false,
                            Name = "Exercise"
                        },
                        new
                        {
                            Id = 21,
                            IsCustom = false,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 22,
                            IsCustom = false,
                            Name = "Writing"
                        },
                        new
                        {
                            Id = 23,
                            IsCustom = false,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 24,
                            IsCustom = false,
                            Name = "Meditation"
                        },
                        new
                        {
                            Id = 25,
                            IsCustom = false,
                            Name = "Yoga"
                        },
                        new
                        {
                            Id = 26,
                            IsCustom = false,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 27,
                            IsCustom = false,
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 28,
                            IsCustom = false,
                            Name = "Parenting"
                        },
                        new
                        {
                            Id = 29,
                            IsCustom = false,
                            Name = "Projects"
                        },
                        new
                        {
                            Id = 30,
                            IsCustom = false,
                            Name = "Planning"
                        },
                        new
                        {
                            Id = 31,
                            IsCustom = false,
                            Name = "Reflection"
                        });
                });

            modelBuilder.Entity("JournalEntryTag", b =>
                {
                    b.Property<int>("JournalEntriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JournalEntriesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("JournalEntryTag");
                });

            modelBuilder.Entity("JournalApp.Models.JournalEntry", b =>
                {
                    b.HasOne("JournalApp.Models.Mood", "PrimaryMood")
                        .WithMany()
                        .HasForeignKey("PrimaryMoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JournalApp.Models.Mood", "SecondaryMood1")
                        .WithMany()
                        .HasForeignKey("SecondaryMood1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JournalApp.Models.Mood", "SecondaryMood2")
                        .WithMany()
                        .HasForeignKey("SecondaryMood2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimaryMood");

                    b.Navigation("SecondaryMood1");

                    b.Navigation("SecondaryMood2");
                });

            modelBuilder.Entity("JournalEntryTag", b =>
                {
                    b.HasOne("JournalApp.Models.JournalEntry", null)
                        .WithMany()
                        .HasForeignKey("JournalEntriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JournalApp.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
